import "server-only";
import { asc, eq, sql } from "drizzle-orm";
import { createDb } from "./client";
import { categories, products } from "./schema";
import canonicalHosts from "@/lib/canonical-hosts.json";
import type {
  Insights,
  KeywordGroupSummary,
  ProductCode,
  RoundBrand,
  RoundRow,
} from "@/types/bid-decision";

// Hosts already mapped in worker/lib/canonical_brand.py HOST_TO_BRAND.
// Brands keyed on one of these are NOT subject to first-word heuristic
// suspicion — the brand name came from an explicit map, not a guess.
// Re-generated by `worker/scripts/dump_canonical_hosts.py`.
const CANONICAL_HOSTS = new Set(canonicalHosts as string[]);

const db = createDb();

export async function getProducts() {
  return db.select().from(products).orderBy(asc(products.id));
}

export async function getCategoriesLvl1(productCode?: ProductCode) {
  if (!productCode) {
    const rows = await db
      .select({ id: categories.id, name: categories.name })
      .from(categories)
      .where(eq(categories.level, 1))
      .orderBy(asc(categories.name));
    return rows;
  }
  const result = await db.execute<{ id: number; name: string }>(sql`
    SELECT DISTINCT c1.id, c1.name
    FROM categories c1
    JOIN categories c2 ON c2.parent_id = c1.id AND c2.level = 2
    JOIN keyword_groups kg ON kg.category_id = c2.id
    JOIN products p ON p.id = kg.product_id
    WHERE c1.level = 1 AND p.code = ${productCode}
    ORDER BY c1.name
  `);
  return result.rows;
}

export async function getCategoriesLvl2(lvl1Name: string, productCode?: ProductCode) {
  if (!productCode) {
    const result = await db.execute<{ id: number; name: string }>(sql`
      SELECT c2.id, c2.name
      FROM categories c1
      JOIN categories c2 ON c2.parent_id = c1.id AND c2.level = 2
      WHERE c1.level = 1 AND c1.name = ${lvl1Name}
      ORDER BY c2.name
    `);
    return result.rows;
  }
  const result = await db.execute<{ id: number; name: string }>(sql`
    SELECT DISTINCT c2.id, c2.name
    FROM categories c1
    JOIN categories c2 ON c2.parent_id = c1.id AND c2.level = 2
    JOIN keyword_groups kg ON kg.category_id = c2.id
    JOIN products p ON p.id = kg.product_id
    WHERE c1.level = 1 AND c1.name = ${lvl1Name} AND p.code = ${productCode}
    ORDER BY c2.name
  `);
  return result.rows;
}

export async function getKeywordGroups(args: {
  product: ProductCode;
  categoryLvl1: string | null;
  categoryLvl2: string | null;
}) {
  const result = await db.execute<{ id: number; name: string }>(sql`
    SELECT kg.id, kg.name
    FROM keyword_groups kg
    JOIN products p ON p.id = kg.product_id
    JOIN categories c2 ON c2.id = kg.category_id
    JOIN categories c1 ON c1.id = c2.parent_id
    WHERE p.code = ${args.product}
      ${args.categoryLvl1 ? sql`AND c1.name = ${args.categoryLvl1}` : sql``}
      ${args.categoryLvl2 ? sql`AND c2.name = ${args.categoryLvl2}` : sql``}
    ORDER BY kg.name
    LIMIT 500
  `);
  return result.rows;
}

export async function getAllKeywordGroupsForSearch(productCode: ProductCode) {
  const result = await db.execute<{
    id: number;
    name: string;
    cat1: string;
    cat2: string;
  }>(sql`
    SELECT kg.id, kg.name, c1.name AS cat1, c2.name AS cat2
    FROM keyword_groups kg
    JOIN products p ON p.id = kg.product_id
    JOIN categories c2 ON c2.id = kg.category_id
    JOIN categories c1 ON c1.id = c2.parent_id
    WHERE p.code = ${productCode}
    ORDER BY kg.name
  `);
  return result.rows;
}

type HeadRow = {
  keyword_group_id: number;
  keyword_group_name: string;
  product: ProductCode;
  category_lvl1: string;
  category_lvl2: string;
};

type TailRow = {
  round_id: number;
  round_no: number;
  period_start: string;
  period_end: string;
  reference_query_volume: number | null;
  min_bid_price: number | null;
  regular_winning_bid: number | null;
  empty_slots: number | null;
  total_slots: number | null;
  bid_status: string | null;
  brands_scraped_at: string | null;
};

export async function getKeywordGroupSummary(args: {
  keywordGroupId: number;
  lastNRounds: number;
}): Promise<KeywordGroupSummary | null> {
  const head = await db.execute<HeadRow>(sql`
    SELECT
      kg.id AS keyword_group_id,
      kg.name AS keyword_group_name,
      p.code AS product,
      c1.name AS category_lvl1,
      c2.name AS category_lvl2
    FROM keyword_groups kg
    JOIN products p ON p.id = kg.product_id
    JOIN categories c2 ON c2.id = kg.category_id
    JOIN categories c1 ON c1.id = c2.parent_id
    WHERE kg.id = ${args.keywordGroupId}
  `);

  if (head.rows.length === 0) return null;
  const h = head.rows[0];

  const tail = await db.execute<TailRow>(sql`
    SELECT
      r.id AS round_id,
      r.round_no,
      r.period_start::text AS period_start,
      r.period_end::text AS period_end,
      rkg.reference_query_volume,
      rkg.min_bid_price,
      rkg.regular_winning_bid,
      rkg.empty_slots,
      rkg.total_slots,
      -- Compute bid_status dynamically by today (docs/round-lifecycle.md).
      -- Falls back to the stored value for rounds outside the defined windows.
      CASE
        WHEN r.regular_bid_start IS NOT NULL
          AND CURRENT_DATE BETWEEN r.regular_bid_start AND r.regular_bid_end
          THEN '정기입찰'
        WHEN r.rebid_start IS NOT NULL
          AND CURRENT_DATE BETWEEN r.rebid_start AND r.rebid_end
          THEN '재입찰'
        WHEN COALESCE(r.rebid_announce_date, r.regular_announce_date) IS NOT NULL
          AND COALESCE(r.rebid_announce_date, r.regular_announce_date) < CURRENT_DATE
          THEN '입찰기간종료'
        ELSE rkg.bid_status
      END AS bid_status,
      rkg.brands_scraped_at::text AS brands_scraped_at
    FROM round_keyword_groups rkg
    JOIN rounds r ON r.id = rkg.round_id
    WHERE rkg.keyword_group_id = ${args.keywordGroupId}
    ORDER BY r.round_no DESC
    LIMIT ${args.lastNRounds}
  `);

  const brandsResult = await db.execute<{
    round_id: number;
    slot_no: number;
    display_name: string;
    title: string;
    sub_title: string | null;
    description: string | null;
    business_name: string;
    source: string;
    confidence: number | null;
  }>(sql`
    SELECT
      rkg.round_id,
      rb.slot_no,
      b.display_name,
      COALESCE(rb.display_name, b.display_name) AS title,
      rb.sub_title,
      rb.description,
      b.business_name,
      rb.source,
      rb.confidence
    FROM round_brands rb
    JOIN round_keyword_groups rkg ON rkg.id = rb.round_keyword_group_id
    JOIN brands b ON b.id = rb.brand_id
    WHERE rkg.keyword_group_id = ${args.keywordGroupId}
    ORDER BY rb.slot_no
  `);

  const brandsByRound = new Map<number, RoundBrand[]>();
  for (const r of brandsResult.rows) {
    const list = brandsByRound.get(r.round_id) ?? [];
    list.push({
      slotNo: r.slot_no,
      displayName: r.display_name,
      title: r.title,
      subTitle: r.sub_title,
      description: r.description,
      businessName: r.business_name,
      source: r.source as RoundBrand["source"],
      confidence: r.confidence,
    });
    brandsByRound.set(r.round_id, list);
  }

  const roundsAsc: RoundRow[] = tail.rows
    .slice()
    .reverse()
    .map((r) => {
      const scrapedBrandCount = (brandsByRound.get(r.round_id) ?? []).length;
      // Effective empty-slot count:
      //   정기입찰 / 재입찰  → CSV `empty_slots` (= unsold slots, meaningful)
      //   else (집행/종료)   → total_slots - scraped (CSV is forced to 0 post-
      //                       announce so it can't be trusted; the real signal
      //                       is whether the slot actually shows an ad)
      const isBidPhase = r.bid_status === "정기입찰" || r.bid_status === "재입찰";
      let effectiveEmpty: number | null;
      if (isBidPhase) {
        effectiveEmpty = r.empty_slots;
      } else if (
        r.brands_scraped_at != null &&
        r.total_slots != null &&
        r.total_slots > 0
      ) {
        // Only trust the scrape-derived count for rounds we actually
        // monitored. Unmonitored old rounds (no brands_scraped_at) would
        // otherwise show total_slots as "empty" since brand_count = 0.
        effectiveEmpty = Math.max(0, r.total_slots - scrapedBrandCount);
      } else {
        effectiveEmpty = null;
      }
      return {
        roundId: r.round_id,
        roundNo: r.round_no,
        periodStart: r.period_start,
        periodEnd: r.period_end,
        referenceQueryVolume: r.reference_query_volume,
        minBidPrice: r.min_bid_price,
        regularWinningBid: r.regular_winning_bid,
        emptySlots: effectiveEmpty,
        bidStatus: r.bid_status,
        ratio:
          r.regular_winning_bid != null && r.min_bid_price
            ? r.regular_winning_bid / r.min_bid_price
            : null,
        brands: brandsByRound.get(r.round_id) ?? [],
        brandsScrapedAt: r.brands_scraped_at,
      };
    });

  const latestRound = roundsAsc[roundsAsc.length - 1];
  const lastAnnounced = [...roundsAsc]
    .reverse()
    .find((r) => r.regularWinningBid != null);
  // The "current execution" round is the one whose period contains today.
  // If today falls in no round (e.g. between weeks), fall back to the most
  // recent past round that actually has brand data.
  const today = new Date().toISOString().slice(0, 10);
  const activeRound =
    roundsAsc.find((r) => r.periodStart <= today && today <= r.periodEnd) ??
    [...roundsAsc].reverse().find((r) => r.brands.length > 0);
  return {
    keywordGroupId: h.keyword_group_id,
    keywordGroupName: h.keyword_group_name,
    product: h.product,
    categoryLvl1: h.category_lvl1,
    categoryLvl2: h.category_lvl2,
    latestWinning: lastAnnounced?.regularWinningBid ?? null,
    latestEmptySlots: activeRound?.emptySlots ?? latestRound?.emptySlots ?? null,
    latestBrands: activeRound?.brands ?? [],
    latestBrandsScrapedAt: activeRound?.brandsScrapedAt ?? null,
    rounds: roundsAsc,
  };
}

export type HeatmapCell = {
  brandId: number;
  brandDisplayName: string;
  roundNo: number;
  keywordGroupName: string;
  categoryLvl1: string;
  categoryLvl2: string;
  productCode: ProductCode;
  slotNo: number;
};

export async function getBrandHeatmap(args: {
  product: ProductCode;
  categoryLvl1: string | null;
  lastNRounds: number;
}): Promise<HeatmapCell[]> {
  const result = await db.execute<{
    brand_id: number;
    display_name: string;
    round_no: number;
    keyword_group_name: string;
    category_lvl1: string;
    category_lvl2: string;
    product_code: ProductCode;
    slot_no: number;
  }>(sql`
    WITH recent_rounds AS (
      SELECT r.id, r.round_no
      FROM rounds r
      JOIN products p ON p.id = r.product_id
      WHERE p.code = ${args.product}
      ORDER BY r.round_no DESC
      LIMIT ${args.lastNRounds}
    )
    SELECT
      b.id AS brand_id,
      b.display_name,
      r.round_no,
      kg.name AS keyword_group_name,
      c1.name AS category_lvl1,
      c2.name AS category_lvl2,
      p.code AS product_code,
      rb.slot_no
    FROM round_brands rb
    JOIN round_keyword_groups rkg ON rkg.id = rb.round_keyword_group_id
    JOIN recent_rounds r ON r.id = rkg.round_id
    JOIN keyword_groups kg ON kg.id = rkg.keyword_group_id
    JOIN categories c2 ON c2.id = kg.category_id
    JOIN categories c1 ON c1.id = c2.parent_id
    JOIN brands b ON b.id = rb.brand_id
    JOIN products p ON p.id = kg.product_id
    WHERE 1=1
      ${args.categoryLvl1 ? sql`AND c1.name = ${args.categoryLvl1}` : sql``}
    ORDER BY b.display_name, r.round_no DESC
  `);
  return result.rows.map((r) => ({
    brandId: r.brand_id,
    brandDisplayName: r.display_name,
    roundNo: r.round_no,
    keywordGroupName: r.keyword_group_name,
    categoryLvl1: r.category_lvl1,
    categoryLvl2: r.category_lvl2,
    productCode: r.product_code,
    slotNo: r.slot_no,
  }));
}

// ─── Brand tracker queries ──────────────────────────────────────────────────

export type BrandSummary = {
  brandId: number;            // representative brand_id (lowest id with same display_name)
  displayName: string;        // canonical brand name (e.g. "삼성화재")
  businessNames: string[];    // ALL hosts owned by this canonical brand
  totalAppearances: number;
  distinctKeywordGroups: number;
  distinctRounds: number;
  productCodes: string[];
  firstSeenAt: string;
  lastSeenAt: string;
};

export async function getBrandSummaries(): Promise<BrandSummary[]> {
  // Group by canonical display_name so multiple brand rows with the same name
  // (different hosts) merge into one logical brand. The representative
  // brandId is the lowest id in the group — used for URL routing only.
  const result = await db.execute<{
    brand_id: number;
    display_name: string;
    business_names: string[];
    total: number;
    kgs: number;
    rounds: number;
    products: string[];
    first_seen: string;
    last_seen: string;
  }>(sql`
    SELECT
      MIN(b.id)::int AS brand_id,
      b.display_name,
      ARRAY_AGG(DISTINCT b.business_name) AS business_names,
      COUNT(rb.id)::int AS total,
      COUNT(DISTINCT rkg.keyword_group_id)::int AS kgs,
      COUNT(DISTINCT rkg.round_id)::int AS rounds,
      ARRAY_AGG(DISTINCT p.code) AS products,
      MIN(rb.captured_at)::text AS first_seen,
      MAX(rb.captured_at)::text AS last_seen
    FROM brands b
    JOIN round_brands rb ON rb.brand_id = b.id
    JOIN round_keyword_groups rkg ON rkg.id = rb.round_keyword_group_id
    JOIN rounds r ON r.id = rkg.round_id
    JOIN products p ON p.id = r.product_id
    GROUP BY b.display_name
    ORDER BY total DESC, b.display_name
  `);
  return result.rows.map((r) => ({
    brandId: r.brand_id,
    displayName: r.display_name,
    businessNames: r.business_names ?? [],
    totalAppearances: r.total,
    distinctKeywordGroups: r.kgs,
    distinctRounds: r.rounds,
    productCodes: r.products ?? [],
    firstSeenAt: r.first_seen,
    lastSeenAt: r.last_seen,
  }));
}

export type BrandHistoryRow = {
  capturedAt: string;
  roundNo: number;
  productCode: ProductCode;
  categoryLvl1: string;
  categoryLvl2: string;
  keywordGroupName: string;
  slotNo: number;
  /** Renamed from adCopy → title for clarity */
  title: string | null;
  subTitle: string | null;
  description: string | null;
  host: string;               // per-capture landing hostname (from brands row)
  source: string;
  confidence: number | null;
};

export async function getBrandHistory(brandId: number): Promise<{
  brand: {
    displayName: string;
    businessNames: string[];  // ALL hosts under this canonical brand
  } | null;
  history: BrandHistoryRow[];
}> {
  // Resolve the canonical display_name from the given brand_id, then return
  // all history rows whose brand has the SAME display_name (cross-host union).
  const head = await db.execute<{ display_name: string }>(sql`
    SELECT display_name FROM brands WHERE id = ${brandId}
  `);
  if (head.rows.length === 0) return { brand: null, history: [] };
  const displayName = head.rows[0].display_name;

  const hostsResult = await db.execute<{ business_name: string }>(sql`
    SELECT DISTINCT business_name FROM brands WHERE display_name = ${displayName}
  `);

  const result = await db.execute<{
    captured_at: string;
    round_no: number;
    product_code: ProductCode;
    category_lvl1: string;
    category_lvl2: string;
    keyword_group_name: string;
    slot_no: number;
    title: string | null;
    sub_title: string | null;
    description: string | null;
    host: string;
    source: string;
    confidence: number | null;
  }>(sql`
    SELECT
      rb.captured_at::text AS captured_at,
      r.round_no,
      p.code AS product_code,
      c1.name AS category_lvl1,
      c2.name AS category_lvl2,
      kg.name AS keyword_group_name,
      rb.slot_no,
      rb.display_name AS title,
      rb.sub_title,
      rb.description,
      b.business_name AS host,
      rb.source,
      rb.confidence
    FROM brands b
    JOIN round_brands rb ON rb.brand_id = b.id
    JOIN round_keyword_groups rkg ON rkg.id = rb.round_keyword_group_id
    JOIN rounds r ON r.id = rkg.round_id
    JOIN products p ON p.id = r.product_id
    JOIN keyword_groups kg ON kg.id = rkg.keyword_group_id
    JOIN categories c2 ON c2.id = kg.category_id
    JOIN categories c1 ON c1.id = c2.parent_id
    WHERE b.display_name = ${displayName}
    ORDER BY r.round_no DESC, p.code, kg.name, rb.slot_no
  `);

  return {
    brand: {
      displayName,
      businessNames: hostsResult.rows.map((r) => r.business_name),
    },
    history: result.rows.map((r) => ({
      capturedAt: r.captured_at,
      roundNo: r.round_no,
      productCode: r.product_code,
      categoryLvl1: r.category_lvl1,
      categoryLvl2: r.category_lvl2,
      keywordGroupName: r.keyword_group_name,
      slotNo: r.slot_no,
      title: r.title,
      subTitle: r.sub_title,
      description: r.description,
      host: r.host,
      source: r.source,
      confidence: r.confidence,
    })),
  };
}


import {
  computeRecommendation,
  fetchActiveStrategy,
  fetchActiveWeights,
} from "@/lib/strategy";

// Brand crawling was only reliable from round 202622 onwards (5월 마지막 주).
// Earlier rounds didn't have valid brand-scrape data, so we exclude them from
// the vacancy-rate denominator to avoid noise.
const VACANCY_RATE_MIN_ROUND = 202622;

export async function computeInsights(summary: KeywordGroupSummary): Promise<Insights> {
  const monitoredRounds = summary.rounds.filter(
    (r) =>
      r.roundNo >= VACANCY_RATE_MIN_ROUND &&
      (r.brandsScrapedAt != null ||
        r.bidStatus === "정기입찰" ||
        r.bidStatus === "재입찰"),
  );
  const vacancies = monitoredRounds.filter((r) => (r.emptySlots ?? 0) > 0).length;
  const vacancyRate =
    monitoredRounds.length === 0 ? null : vacancies / monitoredRounds.length;

  // Load active strategy + weights ONCE per request (two DB round-trips,
  // executed in parallel). Both helpers fall back to the hardcoded defaults
  // on DB error so the computation never breaks.
  const [activeStrategy, activeWeights] = await Promise.all([
    fetchActiveStrategy(db),
    fetchActiveWeights(db),
  ]);

  const latestMin =
    summary.rounds[summary.rounds.length - 1]?.minBidPrice ?? null;
  const rec = computeRecommendation(
    summary.rounds,
    latestMin,
    summary.product,
    activeWeights,
    activeStrategy,
  );

  // Per-KG backtest: how often would `recommendedHigh` have captured the
  // actual winning_bid on past rounds (using only data BEFORE each round).
  let sims = 0;
  let wins = 0;
  for (let i = 1; i < summary.rounds.length; i++) {
    const test = summary.rounds[i];
    if (test.regularWinningBid == null || test.minBidPrice == null) continue;
    const train = summary.rounds.slice(0, i);
    if (!train.some((t) => t.ratio != null)) continue;
    const r = computeRecommendation(
      train.map((t) => ({ ratio: t.ratio })),
      test.minBidPrice,
      summary.product,
      activeWeights,
      activeStrategy,
    );
    if (r.high == null) continue;
    sims += 1;
    if (r.high >= test.regularWinningBid) wins += 1;
  }
  const hitRate = sims >= 3 ? wins / sims : null;

  return {
    meanRatio: rec.meanRatio,
    vacancyRate,
    recommendedLow: rec.low,
    recommendedHigh: rec.high,
    strategyLabel: rec.strategy.label,
    strategyHint: rec.strategy.hint,
    expectedActualCost: rec.expectedCost,
    hitRate,
    hitRateSims: sims,
  };
}


// ========== Brand-scrape progress ==========

export type CrawlProductProgress = {
  productCode: ProductCode;
  done: number;
  pending: number;
  total: number;
  withBrand: number;
};

export type CycleProgress = {
  // Sequential attempt index in the recent BAT window (1, 2, 3, ...).
  // Under the 1-cycle policy a "cycle" is just one BAT invocation —
  // multiple attempts in a short window are usually crash/interrupt + restart,
  // not multi-pass cycles. Keep the field name for backwards compat.
  cycleNo: number;
  runId: number;
  mode: string;              // "resume" | "full" | "null-only" | "default"
  status: string;            // "started" | "completed" | "failed" | "interrupted"
  startedAt: string;
  completedAt: string | null;
  processed: number;         // KGs processed during this attempt's run_at window
  total: number;             // total active KGs (denominator for the bar)
};

export type CrawlProgress = {
  perProduct: CrawlProductProgress[];
  totals: { done: number; pending: number; total: number; withBrand: number };
  lastKgScrapedAt: string | null;
  lastBrandInsertedAt: string | null;
  rateLast5Min: number;       // KGs processed
  rateLast15Min: number;
  rateLast1Hour: number;
  etaHours: number | null;    // null when no recent activity
  currentRunStatus: string | null;
  currentRunStartedAt: string | null;
  cycles: CycleProgress[];
};

export async function getCrawlProgress(): Promise<CrawlProgress> {
  // Round-scoped progress: a KG counts as "done" once `brands_scraped_at`
  // is set, regardless of which BAT attempt did it. The earlier per-cycle
  // scoping was a 3-cycle-era design — under the 1-cycle policy (2026-06-26),
  // every fresh BAT just shows 0% because the new ingest_run resets the
  // denominator. Show absolute round progress instead.
  const perProductResult = await db.execute<{
    product_code: ProductCode;
    done: number;
    pending: number;
    total: number;
    with_brand: number;
  }>(sql`
    SELECT
      p.code AS product_code,
      COUNT(*) FILTER (WHERE rkg.brands_scraped_at IS NOT NULL)::int AS done,
      COUNT(*) FILTER (WHERE rkg.brands_scraped_at IS NULL)::int AS pending,
      COUNT(*)::int AS total,
      COUNT(*) FILTER (
        WHERE EXISTS (SELECT 1 FROM round_brands rb WHERE rb.round_keyword_group_id = rkg.id)
      )::int AS with_brand
    FROM round_keyword_groups rkg
    JOIN rounds r ON r.id = rkg.round_id
    JOIN keyword_groups kg ON kg.id = rkg.keyword_group_id
    JOIN products p ON p.id = kg.product_id
    WHERE r.period_start <= (NOW() AT TIME ZONE 'Asia/Seoul')::date AND r.period_end >= (NOW() AT TIME ZONE 'Asia/Seoul')::date
    GROUP BY p.code
    ORDER BY p.code
  `);
  const perProduct = perProductResult.rows.map((r) => ({
    productCode: r.product_code,
    done: r.done,
    pending: r.pending,
    total: r.total,
    withBrand: r.with_brand,
  }));
  const totals = perProduct.reduce(
    (acc, p) => ({
      done: acc.done + p.done,
      pending: acc.pending + p.pending,
      total: acc.total + p.total,
      withBrand: acc.withBrand + p.withBrand,
    }),
    { done: 0, pending: 0, total: 0, withBrand: 0 },
  );

  // last activity
  const lastActivityResult = await db.execute<{
    last_kg: string | null;
    last_brand: string | null;
  }>(sql`
    SELECT
      (SELECT MAX(brands_scraped_at)::text FROM round_keyword_groups) AS last_kg,
      (SELECT MAX(captured_at)::text FROM round_brands) AS last_brand
  `);
  const { last_kg: lastKgScrapedAt, last_brand: lastBrandInsertedAt } =
    lastActivityResult.rows[0] ?? { last_kg: null, last_brand: null };

  // recent rates
  const rateResult = await db.execute<{
    r5: number; r15: number; r60: number;
  }>(sql`
    SELECT
      COUNT(*) FILTER (WHERE brands_scraped_at > NOW() - INTERVAL '5 minutes')::int AS r5,
      COUNT(*) FILTER (WHERE brands_scraped_at > NOW() - INTERVAL '15 minutes')::int AS r15,
      COUNT(*) FILTER (WHERE brands_scraped_at > NOW() - INTERVAL '1 hour')::int AS r60
    FROM round_keyword_groups
  `);
  const { r5, r15, r60 } = rateResult.rows[0] ?? { r5: 0, r15: 0, r60: 0 };

  // ETA: prefer 15-min rate (smoother than 5-min)
  const ratePerHour = r15 > 0 ? r15 * 4 : r60;
  const etaHours = ratePerHour > 0 ? totals.pending / ratePerHour : null;

  // current run — only cycle-tagged rows (brand_scrape:*), not legacy ones
  const runResult = await db.execute<{
    status: string | null;
    started_at: string | null;
  }>(sql`
    SELECT status, run_at::text AS started_at
    FROM ingest_runs
    WHERE run_type LIKE 'brand_scrape:%'
    ORDER BY id DESC
    LIMIT 1
  `);
  const currentRun = runResult.rows[0] ?? { status: null, started_at: null };

  // Recent BAT cycles — last 3 brand_scrape:* runs (i.e. the current BAT
  // session). 'brand_scrape' (no colon) is the legacy type; we exclude old
  // stale 'started' rows from before the cycle-tagging feature because
  // they'd otherwise pollute the 3-cycle display.
  const cyclesResult = await db.execute<{
    run_id: number;
    run_type: string;
    status: string;
    started_at: string;
    completed_at: string | null;
    rows_total: number | null;
    rows_inserted: number | null;
    processed: number;
  }>(sql`
    WITH recent AS (
      SELECT id, run_type, status, run_at, completed_at,
             rows_total, rows_inserted,
             LEAD(run_at) OVER (ORDER BY id) AS next_run_at
      FROM ingest_runs
      WHERE run_type LIKE 'brand_scrape:%'
        AND run_at > NOW() - INTERVAL '48 hours'
      ORDER BY id DESC
      LIMIT 3
    )
    SELECT
      r.id AS run_id,
      r.run_type,
      r.status,
      r.run_at::text AS started_at,
      r.completed_at::text AS completed_at,
      r.rows_total,
      r.rows_inserted,
      (
        SELECT COUNT(*)::int FROM round_keyword_groups rkg
        JOIN rounds rd ON rd.id = rkg.round_id
        WHERE rd.period_start <= (NOW() AT TIME ZONE 'Asia/Seoul')::date
          AND rd.period_end   >= (NOW() AT TIME ZONE 'Asia/Seoul')::date
          AND rkg.brands_scraped_at >= r.run_at
          AND rkg.brands_scraped_at < COALESCE(r.next_run_at, NOW() + INTERVAL '1 second')
      ) AS processed
    FROM recent r
    ORDER BY r.id ASC
  `);
  const cycles = cyclesResult.rows.map((r, idx) => {
    const mode = r.run_type.replace("brand_scrape:", "").replace("brand_scrape", "default");
    return {
      cycleNo: idx + 1,
      runId: r.run_id,
      mode,
      status: r.status,
      startedAt: r.started_at,
      completedAt: r.completed_at,
      processed: r.processed,
      total: totals.total,
    };
  });

  return {
    perProduct,
    totals,
    lastKgScrapedAt,
    lastBrandInsertedAt,
    rateLast5Min: r5,
    rateLast15Min: r15,
    rateLast1Hour: r60,
    etaHours,
    currentRunStatus: currentRun.status,
    currentRunStartedAt: currentRun.started_at,
    cycles,
  };
}


// ========== Suspect brands needing mapping review ==========

export type SuspectBrand = {
  brandId: number;
  displayName: string;
  businessName: string;
  usesCount: number;          // number of round_brands rows
  hostBroken: boolean;        // host looks malformed (Korean, "주식회사", etc.)
  ad_copies: string[];        // distinct ad copies seen (max 3)
  subTitles: string[];        // distinct sub_titles seen (max 3)
  contexts: { product: ProductCode; keywordGroup: string }[]; // where it's used (max 3)
  reasons: string[];          // why flagged
};

const _HOOK_WORDS = new Set([
  "매장", "9존", "8존", "고함량", "신상", "출시", "신제품", "최대", "특가",
  "오늘만", "1위", "오늘", "단독", "초특가", "이번주", "오직", "지금",
  "고객", "사장", "전국", "프리미엄", "리뉴얼", "정품", "허리가", "두피",
  "음식물", "건강", "안전", "오토", "직접", "쉽고", "기간한정", "할인",
  "당장", "이번", "오로지", "초임계", "공식", "성공하는", "매일을", "중고차,",
]);

function _isHostBroken(host: string): boolean {
  if (!host) return true;
  // host has whitespace, parens, "주식회사", non-ASCII letters, etc.
  if (/[\s()]/.test(host)) return true;
  if (host.includes("주식회사") || host.includes("회사명")) return true;
  if (host.startsWith("__unverified__")) return true;
  // host contains Korean characters
  if (/[가-힣]/.test(host)) return true;
  return false;
}

export async function getSuspectBrands(): Promise<SuspectBrand[]> {
  // Fetch all brands + their ad copies + usage info
  const result = await db.execute<{
    brand_id: number;
    display_name: string;
    business_name: string;
    uses: number;
    ad_copies: string[] | null;
    sub_titles: string[] | null;
    contexts: { product: ProductCode; kg: string }[] | null;
  }>(sql`
    SELECT
      b.id AS brand_id,
      b.display_name,
      b.business_name,
      COUNT(rb.id)::int AS uses,
      array_agg(DISTINCT rb.display_name) FILTER (WHERE rb.display_name IS NOT NULL) AS ad_copies,
      array_agg(DISTINCT rb.sub_title) FILTER (WHERE rb.sub_title IS NOT NULL) AS sub_titles,
      array_agg(DISTINCT jsonb_build_object('product', p.code, 'kg', kg.name))
        FILTER (WHERE kg.name IS NOT NULL) AS contexts
    FROM brands b
    LEFT JOIN round_brands rb ON rb.brand_id = b.id
    LEFT JOIN round_keyword_groups rkg ON rkg.id = rb.round_keyword_group_id
    LEFT JOIN keyword_groups kg ON kg.id = rkg.keyword_group_id
    LEFT JOIN products p ON p.id = kg.product_id
    GROUP BY b.id, b.display_name, b.business_name
    HAVING COUNT(rb.id) > 0
    ORDER BY COUNT(rb.id) DESC, b.id
  `);

  const suspects: SuspectBrand[] = [];

  for (const r of result.rows) {
    if (!r.display_name || !r.business_name) continue;
    const reasons: string[] = [];
    const display = r.display_name.trim();
    const host = r.business_name.trim();
    const copies = (r.ad_copies ?? []).filter(Boolean);
    const subs = (r.sub_titles ?? []).filter(Boolean);

    // Reason 1: host is broken. A junk-looking host (sentinel, parens,
    // Korean text, …) is normally a red flag, but once the operator has
    // explicitly registered it in HOST_TO_BRAND (so it shows up in
    // CANONICAL_HOSTS) the brand is correctly identified — the sentinel is
    // just a permanent placeholder for an advertiser whose landing page
    // we can't fetch. Don't relitigate that decision.
    if (_isHostBroken(host) && !CANONICAL_HOSTS.has(host)) {
      reasons.push("호스트 깨짐");
    }
    // Reason 2: display_name == "(미확인 브랜드)". Same exception — once
    // the host is explicitly mapped, the placeholder display will be
    // refreshed on the next reconcile pass; don't flag it here.
    if (display === "(미확인 브랜드)" && !CANONICAL_HOSTS.has(host)) {
      reasons.push("미확인 브랜드");
    }
    // Reason 3: first-word heuristic — only meaningful for brands whose
    // display_name was *guessed* from the ad copy. Skip when the host is
    // already in HOST_TO_BRAND (the display came from an explicit map).
    if (!CANONICAL_HOSTS.has(host)) {
      let firstWordMatch = false;
      for (const c of copies) {
        const first = c.trim().split(/\s+/)[0] ?? "";
        if (first === display) {
          firstWordMatch = true;
          break;
        }
      }
      if (firstWordMatch) {
        if (display.length <= 3) reasons.push("짧은 이름");
        if (_HOOK_WORDS.has(display)) reasons.push("hook 단어");
      }
    }

    if (reasons.length === 0) continue;

    const contexts = (r.contexts ?? [])
      .map((c) => ({ product: c.product, keywordGroup: c.kg }))
      .slice(0, 3);

    suspects.push({
      brandId: r.brand_id,
      displayName: display,
      businessName: host,
      usesCount: r.uses,
      hostBroken: _isHostBroken(host),
      ad_copies: copies.slice(0, 3),
      subTitles: subs.slice(0, 3),
      contexts,
      reasons: [...new Set(reasons)],
    });
  }
  return suspects;
}


// ========== Backtest (Tier 1 validation) ==========

export type BacktestRow = {
  kgId: number;
  kgName: string;
  product: ProductCode;
  roundNo: number;
  actualWinning: number;
  actualMinBid: number;
  recLow: number | null;
  recHigh: number | null;
  expectedCost: number | null;
  /** Would we have won if we bid recHigh? */
  wouldWin: boolean | null;
  /** recHigh - actualWinning (positive = overpay, negative = underbid). */
  diff: number | null;
};

export type BacktestAggregate = {
  product: ProductCode;
  totalSimulations: number;
  wins: number;
  winRate: number;
  avgOverpayWhenWon: number;
  avgUnderbidWhenLost: number;
};

export type BacktestResult = {
  rows: BacktestRow[];
  aggregates: BacktestAggregate[];
  perKg: {
    kgId: number;
    kgName: string;
    product: ProductCode;
    simulations: number;
    wins: number;
    winRate: number;
    lastRoundDiff: number | null;
  }[];
};

/**
 * Honest out-of-sample backtest. For every (KG, round) where a winning_bid
 * is known, simulate what the recommendation would have been using ONLY
 * data from rounds with a smaller round_no. Then compare to actual.
 *
 * Selection bias note: rounds where we have a winning_bid AND a min_bid_price
 * AND at least one prior round with a settled winning_bid are eligible.
 */
export async function getBacktestResults(): Promise<BacktestResult> {
  // Fetch all (KG, round) with min_bid and winning_bid, in deterministic order.
  const raw = await db.execute<{
    kg_id: number;
    kg_name: string;
    product: ProductCode;
    round_no: number;
    min_bid: number | null;
    winning_bid: number | null;
  }>(sql`
    SELECT
      kg.id AS kg_id,
      kg.name AS kg_name,
      p.code AS product,
      r.round_no,
      rkg.min_bid_price AS min_bid,
      rkg.regular_winning_bid AS winning_bid
    FROM round_keyword_groups rkg
    JOIN rounds r ON r.id = rkg.round_id
    JOIN keyword_groups kg ON kg.id = rkg.keyword_group_id
    JOIN products p ON p.id = kg.product_id
    WHERE rkg.min_bid_price IS NOT NULL
    ORDER BY kg.id, r.round_no
  `);

  // Group rows per KG, ASC by round_no
  const byKg = new Map<number, {
    kgId: number; kgName: string; product: ProductCode;
    rounds: { roundNo: number; minBid: number; winning: number | null; ratio: number | null }[];
  }>();
  for (const r of raw.rows) {
    if (r.min_bid == null) continue;
    const ratio =
      r.winning_bid != null && r.min_bid > 0 ? r.winning_bid / r.min_bid : null;
    const entry = byKg.get(r.kg_id) ?? {
      kgId: r.kg_id,
      kgName: r.kg_name,
      product: r.product,
      rounds: [],
    };
    entry.rounds.push({
      roundNo: r.round_no,
      minBid: r.min_bid,
      winning: r.winning_bid,
      ratio,
    });
    byKg.set(r.kg_id, entry);
  }

  // Load active strategy + weights ONCE before iterating thousands of (KG,
  // round) simulations. fetch helpers fall back to hardcoded defaults on
  // DB error.
  const [activeStrategy, activeWeights] = await Promise.all([
    fetchActiveStrategy(db),
    fetchActiveWeights(db),
  ]);

  const rows: BacktestRow[] = [];
  for (const kg of byKg.values()) {
    // Iterate rounds; for each round with a known winning_bid, use only
    // rounds STRICTLY BEFORE it as training data.
    for (let i = 1; i < kg.rounds.length; i++) {
      const test = kg.rounds[i];
      if (test.winning == null) continue;
      const train = kg.rounds.slice(0, i);
      // Need at least one prior round with a settled ratio.
      if (!train.some((t) => t.ratio != null)) continue;
      const rec = computeRecommendation(
        train.map((t) => ({ ratio: t.ratio })),
        test.minBid,
        kg.product,
        activeWeights,
        activeStrategy,
      );
      if (rec.high == null) continue;
      const diff = rec.high - test.winning;
      rows.push({
        kgId: kg.kgId,
        kgName: kg.kgName,
        product: kg.product,
        roundNo: test.roundNo,
        actualWinning: test.winning,
        actualMinBid: test.minBid,
        recLow: rec.low,
        recHigh: rec.high,
        expectedCost: rec.expectedCost,
        wouldWin: rec.high >= test.winning,
        diff,
      });
    }
  }

  // Per-product aggregates
  const byProduct = new Map<ProductCode, BacktestRow[]>();
  for (const r of rows) {
    const arr = byProduct.get(r.product) ?? [];
    arr.push(r);
    byProduct.set(r.product, arr);
  }
  const aggregates: BacktestAggregate[] = [];
  for (const [product, list] of byProduct) {
    const wins = list.filter((r) => r.wouldWin === true);
    const losses = list.filter((r) => r.wouldWin === false);
    aggregates.push({
      product,
      totalSimulations: list.length,
      wins: wins.length,
      winRate: list.length > 0 ? wins.length / list.length : 0,
      avgOverpayWhenWon:
        wins.length > 0
          ? wins.reduce((s, r) => s + (r.diff ?? 0), 0) / wins.length
          : 0,
      avgUnderbidWhenLost:
        losses.length > 0
          ? losses.reduce((s, r) => s + Math.abs(r.diff ?? 0), 0) / losses.length
          : 0,
    });
  }

  // Per-KG roll-up
  const perKgMap = new Map<number, BacktestRow[]>();
  for (const r of rows) {
    const arr = perKgMap.get(r.kgId) ?? [];
    arr.push(r);
    perKgMap.set(r.kgId, arr);
  }
  const perKg = Array.from(perKgMap.entries()).map(([kgId, list]) => {
    const wins = list.filter((r) => r.wouldWin === true).length;
    const last = list[list.length - 1];
    return {
      kgId,
      kgName: list[0].kgName,
      product: list[0].product,
      simulations: list.length,
      wins,
      winRate: wins / list.length,
      lastRoundDiff: last?.diff ?? null,
    };
  });
  perKg.sort((a, b) => a.winRate - b.winRate); // worst first

  return { rows, aggregates, perKg };
}


// ========== Strategy parameter tuning (Tier 2, in-process) ==========

export type TuneCandidate = {
  weights: number[];
  lowPercentile: number;
  highPercentile: number;
  lowPremium: number;
  highPremium: number;
};

export type TuneMetrics = {
  candidate: TuneCandidate;
  sims: number;
  wins: number;
  winRate: number;
  avgOverpayWhenWon: number;
  avgUnderbidWhenLost: number;
  score: number;
};

export type TuneResult = {
  product: ProductCode;
  evaluated: number;        // # of candidates that had enough sims
  top: TuneMetrics[];
};

function wPctile(
  values: { ratio: number; weight: number }[],
  pct: number,
): number | null {
  if (values.length === 0) return null;
  const sorted = [...values].sort((a, b) => a.ratio - b.ratio);
  const total = sorted.reduce((s, v) => s + v.weight, 0);
  if (total <= 0) return sorted[sorted.length - 1].ratio;
  let cum = 0;
  for (const v of sorted) {
    cum += v.weight;
    if (cum / total >= pct) return v.ratio;
  }
  return sorted[sorted.length - 1].ratio;
}

function simulateHigh(
  trainRatios: number[],
  testMinBid: number,
  c: TuneCandidate,
): number | null {
  const weighted: { ratio: number; weight: number }[] = [];
  // newest first
  for (let i = 0; i < trainRatios.length && i < c.weights.length; i++) {
    const w = c.weights[i];
    if (w <= 0) continue;
    const r = trainRatios[trainRatios.length - 1 - i];
    weighted.push({ ratio: r, weight: w });
  }
  if (weighted.length === 0) return null;
  const high = wPctile(weighted, c.highPercentile);
  if (high == null) return null;
  return Math.round((testMinBid * high * c.highPremium) / 1000) * 1000;
}

export async function tuneStrategy(opts?: {
  topN?: number;
  minSims?: number;
}): Promise<TuneResult[]> {
  const topN = opts?.topN ?? 10;
  const minSims = opts?.minSims ?? 50;

  // Pull the same history backtest uses
  const raw = await db.execute<{
    kg_id: number;
    product: ProductCode;
    round_no: number;
    min_bid: number | null;
    winning_bid: number | null;
  }>(sql`
    SELECT kg.id AS kg_id, p.code AS product, r.round_no,
           rkg.min_bid_price AS min_bid, rkg.regular_winning_bid AS winning_bid
    FROM round_keyword_groups rkg
    JOIN rounds r ON r.id = rkg.round_id
    JOIN keyword_groups kg ON kg.id = rkg.keyword_group_id
    JOIN products p ON p.id = kg.product_id
    WHERE rkg.min_bid_price IS NOT NULL
    ORDER BY kg.id, r.round_no
  `);

  // Group per KG
  type KgRow = { product: ProductCode; rounds: { minBid: number; winning: number | null }[] };
  const kgs = new Map<number, KgRow>();
  for (const r of raw.rows) {
    if (r.min_bid == null) continue;
    const e = kgs.get(r.kg_id) ?? { product: r.product, rounds: [] };
    e.rounds.push({ minBid: r.min_bid, winning: r.winning_bid });
    kgs.set(r.kg_id, e);
  }

  // Build candidate grid
  const weightOptions: number[][] = [
    [4, 3, 2, 1],
    [5, 3, 2, 1],
    [4, 4, 2, 1],
    [3, 3, 2, 1],
    [4, 3, 2, 0],
    [5, 3, 1, 0],
    [6, 4, 2, 1],
  ];
  const lowPcts = [0.3, 0.4, 0.5, 0.6];
  const highPcts = [0.7, 0.8, 0.9, 0.95];
  const lowMuls = [0.95, 1.0, 1.05, 1.1, 1.2];
  const highMuls = [1.05, 1.1, 1.2, 1.3, 1.4, 1.5];
  const candidates: TuneCandidate[] = [];
  for (const w of weightOptions)
    for (const lp of lowPcts)
      for (const hp of highPcts) {
        if (lp >= hp) continue;
        for (const lm of lowMuls)
          for (const hm of highMuls) {
            if (lm > hm) continue;
            candidates.push({
              weights: w,
              lowPercentile: lp,
              highPercentile: hp,
              lowPremium: lm,
              highPremium: hm,
            });
          }
      }

  const products: ProductCode[] = ["SEARCHING_VIEW", "NEW_PRODUCT"];
  const results: TuneResult[] = [];

  for (const product of products) {
    // Precompute per-KG ratio histories for this product
    type KgTrain = { rounds: { ratio: number | null; minBid: number; winning: number | null }[] };
    const trainKgs: KgTrain[] = [];
    for (const kg of kgs.values()) {
      if (kg.product !== product) continue;
      const rounds = kg.rounds.map((r) => ({
        ratio: r.winning != null && r.minBid > 0 ? r.winning / r.minBid : null,
        minBid: r.minBid,
        winning: r.winning,
      }));
      trainKgs.push({ rounds });
    }

    const candResults: TuneMetrics[] = [];
    for (const c of candidates) {
      let sims = 0;
      let wins = 0;
      let overpaySum = 0;
      let overpayN = 0;
      let underbidSum = 0;
      let underbidN = 0;

      for (const kg of trainKgs) {
        const ratios: number[] = [];
        for (let i = 0; i < kg.rounds.length; i++) {
          const row = kg.rounds[i];
          if (row.winning == null) {
            continue;
          }
          if (ratios.length > 0) {
            const recHigh = simulateHigh(ratios, row.minBid, c);
            if (recHigh != null) {
              sims += 1;
              if (recHigh >= row.winning) {
                wins += 1;
                overpaySum += recHigh - row.winning;
                overpayN += 1;
              } else {
                underbidSum += row.winning - recHigh;
                underbidN += 1;
              }
            }
          }
          if (row.ratio != null) ratios.push(row.ratio);
        }
      }

      if (sims < minSims) continue;
      const winRate = sims > 0 ? wins / sims : 0;
      const avgOver = overpayN > 0 ? overpaySum / overpayN : 0;
      const avgUnder = underbidN > 0 ? underbidSum / underbidN : 0;
      const score = winRate - 0.5 * (avgOver / 1_000_000) - 1.0 * (avgUnder / 1_000_000);
      candResults.push({
        candidate: c,
        sims,
        wins,
        winRate,
        avgOverpayWhenWon: avgOver,
        avgUnderbidWhenLost: avgUnder,
        score,
      });
    }

    candResults.sort((a, b) => b.score - a.score);
    results.push({
      product,
      evaluated: candResults.length,
      top: candResults.slice(0, topN),
    });
  }

  return results;
}

// ---------------------------------------------------------------------------
// 광고 누락 의심 KG (scrape miss alerts)
//
// 운영상 발견: NP recall은 4주 연속 16~18%. 이 중 일부는 진짜 누락이고
// 일부는 NOSP total_slots가 운영 광고주 수보다 큰 메타데이터 오류다.
// 두 케이스를 구분하려면 우리 스크랩이 실제로 본 슬롯 수가 필요한데,
// `detected_slot_count`가 그 신호다 (peak single-fetch unique ad_ids).
// ---------------------------------------------------------------------------

export type ScrapeMiss = {
  rkgId: number;
  keywordGroup: string;
  product: ProductCode;
  roundNo: number;
  periodStart: string;
  periodEnd: string;
  totalSlots: number;
  detectedSlotCount: number; // peak single-fetch slot count we observed
  caughtCount: number;       // round_brands rows we persisted
  regularWinningBid: number | null;
  brandsScrapedAt: string | null;
  severity: "real_miss" | "nosp_mismatch" | "never_scraped";
};

export async function getScrapeMisses(): Promise<ScrapeMiss[]> {
  // Three buckets:
  //  - real_miss      : detected_slot_count > caught_count   (we saw it, didn't capture)
  //  - nosp_mismatch  : detected = caught, but NOSP total_slots > detected
  //                     (we captured everything visible, but NOSP says there
  //                      should be more — usually 1-slot KGs flagged as 2)
  //  - never_scraped  : brands_scraped_at IS NULL AND regular_winning_bid > 0
  //                     (KG with a winning bid that never made it through the
  //                      crawler — usually because the BAT didn't reach it)
  const result = await db.execute<{
    rkg_id: number;
    keyword_group: string;
    product: ProductCode;
    round_no: number;
    period_start: string;
    period_end: string;
    total_slots: number;
    detected_slot_count: number | null;
    caught_count: number;
    regular_winning_bid: number | null;
    brands_scraped_at: string | null;
    severity: ScrapeMiss["severity"];
  }>(sql`
    WITH active AS (
      SELECT rkg.id, kg.name AS keyword_group, p.code AS product,
             r.round_no, r.period_start, r.period_end,
             rkg.total_slots, rkg.detected_slot_count,
             rkg.regular_winning_bid, rkg.brands_scraped_at,
             (SELECT COUNT(*)::int FROM round_brands rb
              WHERE rb.round_keyword_group_id = rkg.id) AS caught_count
      FROM round_keyword_groups rkg
      JOIN rounds r ON r.id = rkg.round_id
      JOIN keyword_groups kg ON kg.id = rkg.keyword_group_id
      JOIN products p ON p.id = kg.product_id
      WHERE r.period_start <= (NOW() AT TIME ZONE 'Asia/Seoul')::date AND r.period_end >= (NOW() AT TIME ZONE 'Asia/Seoul')::date
    )
    SELECT id AS rkg_id, keyword_group, product, round_no,
           period_start::text, period_end::text, total_slots,
           detected_slot_count, caught_count,
           regular_winning_bid, brands_scraped_at::text,
           CASE
             WHEN brands_scraped_at IS NULL AND regular_winning_bid > 0
               THEN 'never_scraped'
             -- real_miss requires detected to be plausible (≤ NOSP capacity).
             -- Above that it's almost certainly ad_id-counting noise from a
             -- page with multiple NP widgets, not a true missed advertiser.
             WHEN detected_slot_count IS NOT NULL
                  AND detected_slot_count > caught_count
                  AND detected_slot_count <= total_slots
               THEN 'real_miss'
             WHEN detected_slot_count IS NOT NULL
                  AND detected_slot_count = caught_count
                  AND total_slots > detected_slot_count
               THEN 'nosp_mismatch'
             ELSE NULL
           END AS severity
    FROM active
    WHERE (
      (brands_scraped_at IS NULL AND regular_winning_bid > 0)
      OR (detected_slot_count IS NOT NULL
          AND detected_slot_count > caught_count
          AND detected_slot_count <= total_slots)
      OR (detected_slot_count IS NOT NULL
          AND detected_slot_count = caught_count
          AND total_slots > detected_slot_count)
    )
    ORDER BY
      CASE
        WHEN brands_scraped_at IS NULL THEN 0
        WHEN detected_slot_count > caught_count THEN 1
        ELSE 2
      END,
      regular_winning_bid DESC NULLS LAST
  `);

  return result.rows.map((r) => ({
    rkgId: r.rkg_id,
    keywordGroup: r.keyword_group,
    product: r.product,
    roundNo: r.round_no,
    periodStart: r.period_start,
    periodEnd: r.period_end,
    totalSlots: r.total_slots,
    detectedSlotCount: r.detected_slot_count ?? 0,
    caughtCount: r.caught_count,
    regularWinningBid: r.regular_winning_bid,
    brandsScrapedAt: r.brands_scraped_at,
    severity: r.severity,
  }));
}
